version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: nest
    networks:
      - myapp-network
  test-db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: nest
    networks:
      - myapp-network
networks:
  myapp-network:

# version: '3.8'
# services:
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: admin123
#     ports:
#       - "5050:80"
#     networks:
#       - pgnetwork

#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     networks:
#       - pgnetwork

# networks:
#   pgnetwork:

# Access pgAdmin:

# Go to http://localhost:5050

# Login with:

# Email: admin@example.com

# Password: admin123